### ISSUE TITLE
Javascript library websocket library is not working with CRIS web sockets.

### ISSUE THREAD

**Issue by HAZARATHREDDYN** [Azure-Samples/SpeechToText-WebSockets-Javascript#26]
Hi, 

As per updated document "https://docs.microsoft.com/en-us/azure/cognitive-services/custom-speech-service/customspeech-how-to-topics/cognitive-services-custom-speech-use-endpoint"

by replacing Host "wss://speech.platform.bing.com" with "wss://1234567890.api.cris.ai" is not working.
![cris-connection-issues](https://user-images.githubusercontent.com/30891263/29159046-df4c0d4a-7dca-11e7-9dc3-a99e133acca1.PNG)

please look into the attached screen shot and  help me.

**Comment by andreasla** [comment]
Hi HAZARATHREDDYN,
your screenshot shows that your request still goes against wss://speech.platform.bing.com. You might have to rebuild the JavaScript application with "gulp build". After that reload the page in your browser. Then it should use the host name you entered.

Please make sure to use the host name from your your deployments details page in cris.ai instead of the sample 1234567890.api.cris.ai.

Thanks,

Andreas

**Comment by HAZARATHREDDYN** [comment]
Thanks for your quick response Andreas.

Here i am attaching the correct screen shot.

![cris - error](https://user-images.githubusercontent.com/30891263/29202767-d421ae66-7e88-11e7-93b2-52e479df1713.PNG)

Below one is the request what is going to cris.
Which includes authentication key and connection id (GUID)

wss://86d62036234142a68bf74ef3f36d8f73.api.cris.ai/speech/recognition/conversation/cognitiveservices/v1?format=simple&language=en-US&Ocp-Apim-Subscription-Key=13072365688645668cb897f087b70a5e&X-ConnectionId=6D269F3247004EFD93A97E5681DEF3B9.

I have verified proxy settings also. I dont have any problem with rest api.  I have replaced Bing url with cris url in entire application and tested instead of building. While building with gulp i am getting below error. I am new to this typescript.  Is it mandatory to build because i am replacing host in the entire application.

Kindly help me.

**Comment by andreasla** [comment]
Thank you for sharing these details. I think you can ignore the errors from TypeScript. I have checked the logs of your Custom Speech endpoint, and I can see some request arriving there. Therefore, I think you have done the right changes to the sample.

Our logs show that the service cannot upgrade the initial HTTP request to a web socket connection. Could this be a proxy issue on your side? Can you send requests without going through a proxy? Does the sample work for you with the Bing Speech endpoint and subscription key instead of Custom Speech Service (without the changes to the code)?

By the way, since you have included your subscription key in your post, I suggest to regenerate and/or edit the post.

Thank you,

Andreas

**Comment by HAZARATHREDDYN** [comment]
Thanks Andreas.

Bing speech is working fine. There is no issues with Bing speech end point.  With out any changes to code it works good by replacing Bing speech key and web socket end point.

Disabled proxy and then tried. Getting same issue with cris but Bing is working fine.

**Comment by andreasla** [comment]
Thank you for helping to narrow down the problem. I'll investigate the issue more thoroughly.

**Comment by andreasla** [comment]
Unfortunately, I have not been able to reproduce your problem. I still believe that this issue is related to the proxy server. In the logs of your endpoint I can see some requests today (UTC) that have headers from a proxy. However, I cannot see any other requests arriving at the service since last Friday. This means that your tests with the proxy server disabled did not reach the service at all.

Another thing you could try is to try a different browser to see if the issue occurs there as well.

**Comment by HAZARATHREDDYN** [comment]
Hi after spending lot of time finally came to know that there is network Policy replication issue from our end. Now it is working fine.  Thanks Andreas
